[auth]
redirect_uri = "<REDIRECT_URI_ENV>"

cookie_secret = "oauth-token"

[auth.microsoft]
client_id = "<CLIENT_ID_ENV>"
client_secret = "<CLIENT_SECRET_ENV>"
server_metadata_url = "<SERVER_METADATA_URL_ENV>"